/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.bean.Cargo;
import model.bean.Usuario;
import model.dao.UsuarioDAO;

/**
 *
 * @author rodrigo
 */
public class jfEditarUsuario extends javax.swing.JFrame {

    Vector<Cargo> cargos;
    Usuario objUsuario;
    UsuarioDAO DAO;
    Cargo objCargo;

    public jfEditarUsuario(String user) {
        initComponents();
        jtPesquisaUsuario.setText(user);
        try {
            DAO = new UsuarioDAO();
            objUsuario = new Usuario();
            objCargo = new Cargo();

            cargos = DAO.listarCargos();
            verificarCargos();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }

    private jfEditarUsuario() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlNomeUsuario = new javax.swing.JLabel();
        jlEmail = new javax.swing.JLabel();
        jlLogin = new javax.swing.JLabel();
        jlSenha = new javax.swing.JLabel();
        cbCargo = new javax.swing.JComboBox<Object>();
        jlCargo = new javax.swing.JLabel();
        jtNomUsuario = new javax.swing.JTextField();
        jtDesEmail = new javax.swing.JTextField();
        jtDesLogin = new javax.swing.JTextField();
        jbSalvar = new javax.swing.JButton();
        jbSair = new javax.swing.JButton();
        jbAjuda = new javax.swing.JButton();
        jpSenha = new javax.swing.JPasswordField();
        jlPesquisarUsuario = new javax.swing.JLabel();
        jtPesquisaUsuario = new javax.swing.JTextField();
        jbPreencherCampos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar usuário");
        setResizable(false);

        jlNomeUsuario.setText("Nome:");

        jlEmail.setText("E-mail:");

        jlLogin.setText("Login:");

        jlSenha.setText("Senha:");

        jlCargo.setText("Cargo: ");

        jbSalvar.setText("Salvar alteracoes");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarAlteracoesActionPerformed(evt);
            }
        });

        jbSair.setText("Sair");
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });

        jbAjuda.setText("Ajuda");
        jbAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAjudaActionPerformed(evt);
            }
        });

        jlPesquisarUsuario.setText("Pesquisar usuario:");

        jtPesquisaUsuario.setEditable(false);

        jbPreencherCampos.setText("Preencher Campos");
        jbPreencherCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPreencherCamposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlNomeUsuario)
                            .addComponent(jlEmail)
                            .addComponent(jlLogin)
                            .addComponent(jlSenha)
                            .addComponent(jlPesquisarUsuario))
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlCargo)
                        .addGap(34, 34, 34)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtDesEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtNomUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jtPesquisaUsuario)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbPreencherCampos))
                        .addComponent(jtDesLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jpSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jbSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSair)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbAjuda)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPesquisarUsuario)
                    .addComponent(jtPesquisaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPreencherCampos))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtNomUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jlNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEmail)
                    .addComponent(jtDesEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlLogin)
                    .addComponent(jtDesLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCargo)
                    .addComponent(cbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalvar)
                    .addComponent(jbSair)
                    .addComponent(jbAjuda))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAjudaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Ajuda para criar novo usuario do sistema.\nNo campo Nome: O sistema preenchera automaticamente com o seu login de acesso ao sistema\n"
                + "Ao clicar no botão 'Preencher Campos os dados cadastrados do usuário serão preenchido nas caixas de texto para que ele possa altera-los.\n"
                + "Na caixa de combinação 'Cargo' o usuário devera selecionar o seu cargo exercido na instituição.\n"
                + "Após realizar as alterações desejadas clicar no botão 'Salvar Alterações' para salvar os novos dados e após concluir a operação o\n"
                + "sistema retornara a tela do menu principal.\n"
                + "Se o usuário não quiser realizar alterações em seu cadastro, ele devera clicar no botão 'Sair', e o sistema retornara a tela de menu principal.\n"
                + "No botão ajuda é exibido a tela com instruções de uso da funcionabilidade.\n");
    }//GEN-LAST:event_jbAjudaActionPerformed

    private void jbSalvarAlteracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarAlteracoesActionPerformed
        try {
            if (validarCampos()) {
                if (preencherObjeto()) {
                    if (DAO.editarUsuario(objUsuario)) {
                        JOptionPane.showMessageDialog(this, "Alterações salvas com sucesso!");
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, "Não foi possivel fazer as alterações!");
                        limparCampos();
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_jbSalvarAlteracoesActionPerformed

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        dispose();
    }//GEN-LAST:event_jbSairActionPerformed

    private void jbPreencherCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPreencherCamposActionPerformed
        try {
            if (jtPesquisaUsuario.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Entre com o nome do usuario!");
                jtPesquisaUsuario.requestFocus();
            } else {
                objUsuario = DAO.pesquisar(jtPesquisaUsuario.getText());

                if (objUsuario == null) {
                    JOptionPane.showMessageDialog(this, "Usuario nao encontrado!");
                } else {
                    jtNomUsuario.setText(objUsuario.getNomUsuario());
                    jtDesEmail.setText(objUsuario.getDesEmail());
                    jtDesLogin.setText(objUsuario.getDesLogin());
                    jpSenha.setText(objUsuario.getDesSenha());
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao pesquisar!" + ex.getMessage());
        }
    }//GEN-LAST:event_jbPreencherCamposActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfEditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfEditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfEditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfEditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfEditarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Object> cbCargo;
    private javax.swing.JButton jbAjuda;
    private javax.swing.JButton jbPreencherCampos;
    private javax.swing.JButton jbSair;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JLabel jlCargo;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlLogin;
    private javax.swing.JLabel jlNomeUsuario;
    private javax.swing.JLabel jlPesquisarUsuario;
    private javax.swing.JLabel jlSenha;
    private javax.swing.JPasswordField jpSenha;
    private javax.swing.JTextField jtDesEmail;
    private javax.swing.JTextField jtDesLogin;
    private javax.swing.JTextField jtNomUsuario;
    private javax.swing.JTextField jtPesquisaUsuario;
    // End of variables declaration//GEN-END:variables

    public boolean validarCampos() {
        if (jtNomUsuario.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Digite o nome do usuário.");
            jtNomUsuario.requestFocus();
            return false;
        }
        if (jtDesEmail.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Digite o e-mail do usuário.");
            jtDesEmail.requestFocus();
            return false;
        }
        if (jtDesLogin.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Digite o login do usuário.");
            jtDesLogin.requestFocus();
            return false;
        }
        if (jpSenha.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Digite uma senha para o usuário.");
            jpSenha.requestFocus();
            return false;
        }
        return true;
    }

    public void limparCampos() {
        jtNomUsuario.setText("");
        jtDesEmail.setText("");
        jtDesLogin.setText("");
        jpSenha.setText("");
    }

    public void verificarCargos() {
        try {
            if (cargos.size() == 0) {
                Vector msg = new Vector();
                msg.add("Não a cargos cadastrados!");
                cbCargo.setEnabled(false);
                cbCargo.setModel(new DefaultComboBoxModel(msg));
            } else {
                cbCargo.setModel(new DefaultComboBoxModel(cargos));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }

    public boolean preencherObjeto() {
        objUsuario.setNomUsuario(jtNomUsuario.getText());
        objUsuario.setDesEmail(jtDesEmail.getText());
        objUsuario.setDesLogin(jtDesLogin.getText());
        objUsuario.setDesSenha(jpSenha.getText());
        objUsuario.setCargo(cargos.get(cbCargo.getSelectedIndex()));
        return true;
    }
}
