/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.bean.Usuario;
import model.dao.UsuarioDAO;

/**
 *
 * @author rodrigo
 */
public class MDIHome extends javax.swing.JFrame {

    UsuarioDAO userDao = new UsuarioDAO();

    /**
     * Creates new form MDIHome
     */
    public MDIHome(String user) {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        jMenuItemUser.setText(user);
    }

    MDIHome() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPanePrincipal = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenuAgendamento = new javax.swing.JMenu();
        editarUsuarioMenuItem = new javax.swing.JMenuItem();
        consultarAgendamentoMenuItem = new javax.swing.JMenuItem();
        menuCadastrarCargo = new javax.swing.JMenuItem();
        cadastrarEspacoMenuItem = new javax.swing.JMenuItem();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuUser = new javax.swing.JMenu();
        jMenuItemUser = new javax.swing.JMenuItem();
        jMenuItemDesconectar = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        sobreMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenuAgendamento.setMnemonic('f');
        fileMenuAgendamento.setText("Menu");

        editarUsuarioMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        editarUsuarioMenuItem.setText("Editar usuário");
        editarUsuarioMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarUsuarioMenuItemActionPerformed(evt);
            }
        });
        fileMenuAgendamento.add(editarUsuarioMenuItem);

        consultarAgendamentoMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        consultarAgendamentoMenuItem.setMnemonic('s');
        consultarAgendamentoMenuItem.setText("Gerenciar Agendamentos");
        consultarAgendamentoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarAgendamentoMenuItemActionPerformed(evt);
            }
        });
        fileMenuAgendamento.add(consultarAgendamentoMenuItem);

        menuCadastrarCargo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        menuCadastrarCargo.setMnemonic('a');
        menuCadastrarCargo.setText("Cadastrar Cargo");
        menuCadastrarCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarCargoActionPerformed(evt);
            }
        });
        fileMenuAgendamento.add(menuCadastrarCargo);

        cadastrarEspacoMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        cadastrarEspacoMenuItem.setText("Cadastrar novo espaço");
        cadastrarEspacoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarEspacoMenuItemActionPerformed(evt);
            }
        });
        fileMenuAgendamento.add(cadastrarEspacoMenuItem);

        jMenuItemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        fileMenuAgendamento.add(jMenuItemSair);

        menuBar.add(fileMenuAgendamento);

        jMenuUser.setText("Usuário Logado");

        jMenuItemUser.setText("User");
        jMenuUser.add(jMenuItemUser);

        jMenuItemDesconectar.setText("Desconectar");
        jMenuItemDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDesconectarActionPerformed(evt);
            }
        });
        jMenuUser.add(jMenuItemDesconectar);

        menuBar.add(jMenuUser);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Ajuda");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Conteúdo");
        contentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(contentMenuItem);

        sobreMenuItem.setMnemonic('a');
        sobreMenuItem.setText("Sobre");
        sobreMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobreMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(sobreMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPanePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPanePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarEspacoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarEspacoMenuItemActionPerformed
        if (jMenuItemUser.getText().equals("admin")) {
            new jfCadastroEspaco().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Voce não possui permissão para cadastrar um novo espaço!\n"
                    + "Favor entrar em contato com a direção ou supervisão.");
        }
    }//GEN-LAST:event_cadastrarEspacoMenuItemActionPerformed

    private void menuCadastrarCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarCargoActionPerformed
        if (jMenuItemUser.getText().equals("admin")) {
            new jfCadastroCargo().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Voce não possui permissão para cadastrar um novo cargo!\n"
                    + "Favor entrar em contato com a direção ou supervisão.");
        }
    }//GEN-LAST:event_menuCadastrarCargoActionPerformed

    private void editarUsuarioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarUsuarioMenuItemActionPerformed
        new jfEditarUsuario(jMenuItemUser.getText()).setVisible(true);
    }//GEN-LAST:event_editarUsuarioMenuItemActionPerformed

    private void jMenuItemDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDesconectarActionPerformed
        jfLogin login = new jfLogin();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemDesconectarActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void consultarAgendamentoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarAgendamentoMenuItemActionPerformed
        jfConsultarAgendamento consultaAgendamento = new jfConsultarAgendamento();
        consultaAgendamento.setVisible(true);
    }//GEN-LAST:event_consultarAgendamentoMenuItemActionPerformed

    private void sobreMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobreMenuItemActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Sistema de Agendamento de sala.\nVersão 0.1\n"
                + "Projeto Estágio Supervisionado - Faculdade Newton Paiva.\nAluno: Rodrigo de Melo toledo\nE-mail de contato: rodrigomelotoledo@gmail.com");
    }//GEN-LAST:event_sobreMenuItemActionPerformed

    private void contentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItemActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Ajuda do sistema - Barra de menus principal.\n"
                + "Menu: No item de menu 'Menu' onde ficam as funcionabilidades: Editar Usuário, Gerenciar Agendamento, Cadastrar Cargo, Cadastrar\n"
                + " Novo Espaço e sair.\n"
                + "Usuário Logado: Menu onde fica indicando o usuário que fez login no sistema e no item de menu Desconectar, o usuário faz o logoff\n"
                + " de sua conta sem ter que fechar o sistema.\n"
                + "Ajuda: No item de menu Conteúdo, esta a ajuda inicial do sistema, reportando as funções contidas na barra de menu principa do\n"
                + "sistema.\n"
                + "Sobre: No item de menu 'Sobre', está as informações sobre versão do sistema e e-mail de contato para relatar problemas com o sistema.");

    }//GEN-LAST:event_contentMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MDIHome().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadastrarEspacoMenuItem;
    private javax.swing.JMenuItem consultarAgendamentoMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JDesktopPane desktopPanePrincipal;
    private javax.swing.JMenuItem editarUsuarioMenuItem;
    private javax.swing.JMenu fileMenuAgendamento;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem jMenuItemDesconectar;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemUser;
    private javax.swing.JMenu jMenuUser;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuCadastrarCargo;
    private javax.swing.JMenuItem sobreMenuItem;
    // End of variables declaration//GEN-END:variables
}
